In [4]:
print('안녕하세요')
print(100)

안녕하세요
100


In [5]:
# 주석 => 코드 내부에 사용, 코드로 인식 X, 간단한 메모
# 변수 => 데이터를 저장(메모리: 플레시메모리)하는 방식
# 변수이름(식별자) = 값(데이터: 숫자, 문자열, 논리값(True,False), 객체)
# 변수에는 데이터를 저장하고 있는 메모리의 주소값을 저장
num = 10

In [6]:
print(num)

10


In [7]:
id(num)

140724388250824

In [8]:
num+100

110

In [10]:
# 변수 = 데이터
# 데이터 => 숫자, 문자, 논리값
# 숫자 => 정수, 실수
num1 = 10
num2 = 3.14

In [13]:
print(type(num1))
print(type(num2))

<class 'int'>
<class 'float'>


In [14]:
num3 = 'hello~'

In [16]:
print(num3)
print(type(num3))

hello~
<class 'str'>


In [17]:
# 논리값 : 참, 거짓 => True, False
check1 = True
check2 = False

In [19]:
print(check1, type(check1))
print(check2, type(check2))

True <class 'bool'>
False <class 'bool'>


In [25]:
str_a = 'python'

In [26]:
str_a.upper()
# 주소값.메서드()

'PYTHON'

In [27]:
print(type(str_a))

<class 'str'>


In [28]:
str_a = 100

In [29]:
print(str_a, type(str_a))

100 <class 'int'>


In [30]:
# 문자열 생성
# '', "", ''' ''', """ """
str_1 = 'hello~'
str_2 = "안녕하세요"
str_3 = '''첫째 라인
안녕하세요
반갑습니다.
'''
str_4 = """
select *
from emp
where empno=10
"""

In [35]:
print(str_1, type(str_1))
print(str_2, type(str_2))
print(str_3, type(str_3))
print(str_4, type(str_4))

hello~ <class 'str'>
안녕하세요 <class 'str'>
첫째 라인
안녕하세요
반갑습니다.
 <class 'str'>

select *
from emp
where empno=10
 <class 'str'>


In [37]:
# 문자열의 연산
# 사칙연산 X => 더하기(연결)
# 곱샘 * => 반복(몇번 반복)
print('hello'+' python!!')
print('='*10)

hello python!!


In [40]:
# 함수(기능) : 데이터 전달하면 -> 처리(연산) -> 값을 반환
# 문자열의 길이 반환 함수 : len(변수:시퀀스형식의 데이터)
print(len(str_1))
print(len(str_2))

6
5


In [ ]:
# 문자열 : 시퀀스 데이터 => 순서 O
# 시퀀스 데이터의 테이터들의 구분 => index값
# hello => ['h', 'e', 'l', 'l', 'o']
#   index => 0    1    2    3    4   => 0 ~ N-1 => 0~4
str_5 = 'hello~ python!!'
#        0123456789..

In [43]:
str_5[5]

'~'

In [44]:
# 문자열(시퀀스)의 슬라이싱
# s[시작 index : 종료 index]   => 종료 index값을 만나면 탈출
# str_5[0 : 5]
str_5[0 : 5]

'hello'

In [46]:
# 문자열 포맷팅
# 3.6 버전 이후 f""  , 접두사 f 붙이고 포맷팅
user_name = '손흥민'
user_age = 30
print(f'안녕하세요! 저는 {user_name}입니다. 나이는 {user_age} 입니다.')

안녕하세요! 저는 손흥민입니다. 나이는 30 입니다.


In [47]:
print(f'내년에는 나이가 {user_age+1}살이 됩니다.')

내년에는 나이가 31살이 됩니다.


In [48]:
# 복합 대입 연산
num = 1

In [49]:
num = num + 1

In [50]:
print(num)

2


In [51]:
num += 1  # num = num + 1

In [52]:
print(num)

3


### 연습문제 1
과목별 점수, 총점, 평균점수 출력
과목 : 국어, 영어, 수학

In [ ]:
# 1. 변수 선언, 초기화
kor_score = 100     # 국어점수
eng_score = 70      # 영어점수
math_score = 80     # 수학점수

In [ ]:
# 2. 연산 : 총점, 평균
sum_score = kor_score + eng_score + math_score
avg_score = sum_score / 3

In [56]:
# 3. 결과 출력
print(f'국어점수:{kor_score}, 영어점수:{eng_score}, 수학점수: {math_score} \n총점:{sum_score} \n평균점수:{avg_score}')

국어점수:100, 영어점수:70, 수학점수: 80 
총점:250 
평균점수:83.33333333333333


In [60]:
# 성별 체크, 나이 체크
# 성별이 남성이고(and), 성인 판별 (18살 이상)
# 1. 변수
gender = 'M'  # 셩별 : 'M' | 'F'
age = 20

In [61]:
# 2. 남성 그리고 성인
check = gender == 'M' and age >= 18

In [62]:
print('성인 남성 체크 :', check)

성인 남성 체크 : True


In [4]:
# 리스트 : [] =>  순서를 가지는 데이터 묶음
# index 값으로 요소들을 참조 => 0 ~ N(요소의 개수)-1
list_a = [1,2,3]
# index   0 1 2
# 요소의 개수 : 3

In [5]:
print(list_a, type(list_a))

[1, 2, 3] <class 'list'>


In [6]:
# bool(), int(), float(), str(), list()

In [7]:
# 요소의 참조 : 변수처럼 사용
list_a[2]

3

In [10]:
list_a[0] + list_a[1]  # 1 + 2

3

In [8]:
list_a[2] = 4

In [9]:
list_a

[1, 2, 4]

### 2025.06.10

In [12]:
list_a[-2]

2

In [15]:
list_a[ len(list_a)-1 ]  # N-1

4

In [ ]:
list_b = [ 1, 2, 3, ['a', 'b', 'c']]
#          0  1  2         3
#         [int, int, int, list]

In [17]:
len(list_b)

4

In [ ]:
print(list_b[0])
print(list_b[1])
print(list_b[2])
print(list_b[3])  # list
print(list_b[3][0], list_b[3][1], list_b[3][2])
#     list를 가릐는 주소값[index]

1
2
3
['a', 'b', 'c']
a b c


In [25]:
# 슬라이싱
list_c = [1, 2, 3, 4, 5]
#         0  1  2  3  4

In [31]:
list_c[1:4]
list_c[:4]  #  list_c[0:4]
list_c[1:]  # list_c[1:5]
list_c[:]
list_c

[1, 2, 3, 4, 5]

In [32]:
# list의 연산 :  + , * 
list_d = [100, 200, 300]

In [ ]:
list_c
list_d
list_c + list_d # 새로운 리스트 생성
list_d + list_c # 새로운 리스트 생성
list_c
list_d

[100, 200, 300]

In [39]:
# * : 리스트의 요소를 n번 반복해서 저장 -> 새로운 리스트
list_d * 3

[100, 200, 300, 100, 200, 300, 100, 200, 300]

In [40]:
# 리스트에 요소(데이터) 추가 : 순서 => 마지막 인덱스 다음에 데이터 추가 
# append() : 메서드 => 리스트의 마지막에 데이터 추가 
list_a = [1, 2, 3]

In [44]:
list_a.append(500)
# 객체(list)

In [50]:
# pop : 마지막 요소 축출 -> 삭제, 값을 반환
# list_a.pop()
list_a.pop(0)

1

In [51]:
list_a

[2, 3]

In [52]:
list_a = [1, 4, 9, 2, 10]

In [53]:
list_a.sort()

In [54]:
list_a

[1, 2, 4, 9, 10]

In [55]:
list_a.reverse()
list_a

[10, 9, 4, 2, 1]

In [58]:
list_a.index(4)

2

In [59]:
list_a.insert(1, 100)

In [61]:
list_a

[10, 100, 9, 4, 2, 1]

In [63]:
list_a.extend(list_d)

In [64]:
list_a

[10, 100, 9, 4, 2, 1, 100, 200, 300]

In [66]:
# tuple : list와 동일, 
# 단 요소(데이터) 변경은 불가능 -> 데이터 안전하게 유지
t_1 = ()
print(type(t_1))

<class 'tuple'>


In [73]:
t_2 = (1,2,3,4)
t_3 = 10,20,30,40

In [75]:
type(t_3)

tuple

In [78]:
t_3[0]

10

In [79]:
t_2[0] = 100

TypeError: 'tuple' object does not support item assignment

In [80]:
del t_2[0]

TypeError: 'tuple' object doesn't support item deletion

In [82]:
t_3[1:3]

(20, 30)

In [ ]:
a, b, c = 1000, 2000, 3000  # 특정함수에서 반환 데이터 tuple 타입

In [84]:
print(a, b, c)

1000 2000 3000


In [85]:
t_2+t_3

(1, 2, 3, 4, 10, 20, 30, 40)

In [86]:
t_2*3

(1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4)

In [89]:
# 딕셔너리 : key : value => key 값으로 데이터를 참조
# { key1:value1, key2:value2, .... }
dict_1 = {}
print(type(dict_1))
print(dict_1)

<class 'dict'>
{}


In [90]:
dict_2 = {1 : 'a'}
print(dict_2)
print(type(dict_2))

{1: 'a'}
<class 'dict'>


In [91]:
# 요소값 추가 => key 정의, 값 정의
dict_2[2] = 'b'
dict_2

{1: 'a', 2: 'b'}

In [93]:
dict_2[2]

'b'

In [94]:
dict_2[3] = (1,2,3)

In [97]:
del dict_2[3]

In [98]:
dict_2

{1: 'a', 2: 'b'}

In [99]:
# 학생 : 학번, 이름, 학년, 학과 => 데이터의 구조화화
student_1 = {
    's_no': 1111,
    's_name': 'KING',
    'grade': 4,
    'major': 'COM'
}

In [102]:
student_1['grade']

4

In [103]:
player = {
    'team': 'TO',
    'name': 'SON',
    'number': 7
}

In [104]:
player.keys()

dict_keys(['team', 'name', 'number'])

In [105]:
list(player.keys())

['team', 'name', 'number']

In [106]:
player.values()

dict_values(['TO', 'SON', 7])

In [107]:
list(player.values())

['TO', 'SON', 7]

In [110]:
'age' in player

False

In [111]:
player.items()

dict_items([('team', 'TO'), ('name', 'SON'), ('number', 7)])

In [112]:
list_temp = list(player.items())

In [117]:
list_temp

[('team', 'TO'), ('name', 'SON'), ('number', 7)]

In [118]:
player['name']

'SON'

In [120]:
player['pos']

KeyError: 'pos'

In [121]:
player.get('name')

'SON'

In [123]:
pos = player.get('pos')

In [124]:
print(pos)

None


In [125]:
pos1 = player.get('pos', 'no pos')

In [126]:
print(pos1)

no pos


In [127]:
# set : 집합 => 중복 X, 순서 X, 집합 연산 사용
s_1 = set([1,2,3,4,1,2,5])
s_1

{1, 2, 3, 4, 5}

In [128]:
set_2 = set('hello')
set_2

{'e', 'h', 'l', 'o'}

In [129]:
list_1 = list(s_1)
print(list_1)

[1, 2, 3, 4, 5]


In [130]:
set_2 = set([1,2,3,4,5,6])
set_3 = set([4,5,6,7,8,9])

In [133]:
print(set_2 & set_3)
print(set_2 | set_3)
print(set_2 - set_3)

{4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3}


In [136]:
# set 에서 데이터 추가(중복 데이터 입력 X) 삭제
set_2.add(3)

In [139]:
set_2

{1, 2, 3, 4, 5, 6}

In [138]:
set_2.remove(7)

In [140]:
set_2.update([1,1,3,4,7,8])

In [141]:
set_2

{1, 2, 3, 4, 5, 6, 7, 8}

In [143]:
# if : 분기 => ~ 라면, 아니라면
# 성인이라면, 상인이 아니라면
age = 25

# 성인이라면-> 환영 메시지, 미성년 -> 킥~
if age>=18 :
    print('환영합니다~~~')
    print('게임을 시작하세요!')
else :
    print('킥~~~')

환영합니다~~~
게임을 시작하세요!


In [145]:
# 홀수 짝수 판단 => 숫자%2 : 1->홀수, 0->짝수
num = 9

if num%2 == 0 :
    print('짝수')
else :
    print('홀수')

홀수


In [150]:
# 양수 +, => num1 > 0
# 음수 -, => num1 < 0
# 0 => num == 0 => num1이 0보다 작지도 않고 크지도 않다

num1 = 0
if num1 > 0 :
    print('양수')
else :
    if num1 < 0 :
        print('음수')
    else :
        print(0)


0


In [151]:
if num1 > 0 :
    print('양수')
elif num1 < 0 :
    print('음수')
else :
    print(0)


0


In [153]:
# 운전면허 시험
score = 79
check_msg = 'PASS' if score >= 80 else 'FAIL'
print(check_msg)

FAIL


In [154]:
check_msg = 'PASS'
if score < 80 :
    check_msg = 'FAIL'

print(check_msg)

FAIL


In [160]:
# 표준 출력 함수 => print()
# 표준 입력 함수 => input()
user_age = input('나이를 입력하세요!')
print(user_age, type(user_age), 2025-int(user_age))

50 <class 'str'> 1975


In [167]:
age

25

In [166]:
if age < 15 or age >= 65 :
    print('접종 대상자')
else :
    print('접종 대상자 아님')

접종 대상자 아님


In [ ]:
medical_msg = '대상자 아님'

if age < 15 or age >= 65:
    medical_msg = '대상자'

print(medical_msg)

대상자 아님


In [165]:
medical_msg = '대상자' if age < 15 or age >= 65 else '대상자 아님'
print(medical_msg)

대상자 아님


In [168]:
# 반복문 : while condition(True/False) :
# 조건식을 통해서 반복 -> 탈출이 가능해야한다!
cnt = 0

while cnt < 5 :
    cnt = cnt + 1
    print(cnt)

1
2
3
4
5


In [174]:
# 1~10 까지 출력, 홀수만 출력
cnt = 0
while cnt < 10 :
    cnt += 1  # cnt = cnt + 1
    if cnt%2 == 1 :
        print(cnt)

1
3
5
7
9


In [ ]:
cnt = 0
while cnt < 10 :
    cnt += 1
    if cnt%2 == 0:
        continue
    print(cnt)

1
3
5
7
9


In [176]:
list_a = [1,2,3,4,5,100, 200, 300]

In [177]:
for i in list_a:
    print(i)    

1
2
3
4
5
100
200
300


In [178]:
list_b = [(1,2), (3,4), (5,6)]

In [179]:
for n1, n2 in list_b :
    print(n1, n2)

1 2
3 4
5 6


In [184]:
# 5명의 학생이 영어 시험 => 60점 이상 pass 출력
# 5명의 영어점수 총점, 평균

scores = [80, 50, 70, 100, 55]
num = 0     # 학생 리스트의 일련번호
sum = 0     # 총점

for score in scores :
    # 학생의 점수를 비교해서 : pass, fail
    # 리스트의 일련번호 출력 : num = num + 1
    num = num + 1
    sum = sum + score
    if score >= 60 :
        print(num, score, 'PASS')
    else :
        print(num, score, 'Fail')

print('총점 :', sum)
print('평균 :', sum/len(scores))


1 80 PASS
2 50 Fail
3 70 PASS
4 100 PASS
5 55 Fail
총점 : 355
평균 : 71.0


In [185]:
# range 함수 : 일련 번호 생성
nums_1 = range(10) # 0 ~ 10-1

In [187]:
for num in nums_1:
    print(num, end=', ')

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 

In [188]:
for num in range(3, 8) :  # 3, 4, 5, 6, 7
    print(num, end=' ')

3 4 5 6 7 

In [190]:
for num in range(2, 11, 2) :
    print(num , end=' ')

2 4 6 8 10 

In [193]:
# 구구단 : 2~9단  => 2~9
# 각 단 : X 1 ~ X 9 => 1~9
for dan in range(2, 10):
    print(f'{dan} 단')
    for i in range(1, 10):
        print(f'{dan}X{i}={dan*i}', end=' ')
    print()

2 단
2X1=2 2X2=4 2X3=6 2X4=8 2X5=10 2X6=12 2X7=14 2X8=16 2X9=18 
3 단
3X1=3 3X2=6 3X3=9 3X4=12 3X5=15 3X6=18 3X7=21 3X8=24 3X9=27 
4 단
4X1=4 4X2=8 4X3=12 4X4=16 4X5=20 4X6=24 4X7=28 4X8=32 4X9=36 
5 단
5X1=5 5X2=10 5X3=15 5X4=20 5X5=25 5X6=30 5X7=35 5X8=40 5X9=45 
6 단
6X1=6 6X2=12 6X3=18 6X4=24 6X5=30 6X6=36 6X7=42 6X8=48 6X9=54 
7 단
7X1=7 7X2=14 7X3=21 7X4=28 7X5=35 7X6=42 7X7=49 7X8=56 7X9=63 
8 단
8X1=8 8X2=16 8X3=24 8X4=32 8X5=40 8X6=48 8X7=56 8X8=64 8X9=72 
9 단
9X1=9 9X2=18 9X3=27 9X4=36 9X5=45 9X6=54 9X7=63 9X8=72 9X9=81 


In [ ]:
# 리스트의 컴프리헨션
# [표현식 for 변수 in list if 조건식(변수)]

In [196]:
list_2 = [1,2,3,4]

# 결과 리스트
list_result = []
for num in list_2:
    if num%2==1:
        list_result.append(num*3)

print(list_result)

[3, 9]


In [198]:
list_result_2 = [num*3 for num in list_2 if num%2==1]
print(list_result_2)

[3, 9]


In [195]:
list_result_1 = [num*3 for num in list_2]
print(list_result_1)

[3, 6, 9, 12]


### 2025.06.11

In [ ]:
#EX3
# 검진 대상장 판별
# 20세이상, 짝수년도에는 짝수 년생들이 대상
# 40세 이상 암 검진 대상
# 올해 년도 , 태어난 년도 
year = 2025
birth_year = 1985
age = year-birth_year
print(age)

if age>=20 and birth_year%2==year%2 :
    print('검진 대상자입니다.')
    if age >= 40:
        print('암검진 대상자입니다.')
else :
    print('검진대상자가 아닙니다.')



In [1]:
# EX 3-1
# 1부터 100 까지의 합을 구하는 프로그램
sum = 0
for i in range(1, 101):
    #print(i, end=",")
    sum += i

print('sum : ', sum)

sum :  5050


In [2]:
# EX 3-2
# 1부터 10 까지의 곱을 구하는 프로그램
result = 1
for i in range(1, 11):
    #print(i, end=",")
    result *= i

print('result : ', result)

result :  3628800


In [3]:
# 3-3 구구단의 짝수단(2, 4, 6, 8)단만 출력
# 2x2, 4x4, 6x6, 8x8
for dan in range(2, 9, 2):
    print(dan, '단')
    for num in range(1, dan+1):
        print(dan , 'x', num, '=', dan*num, end=' ')
    print()

2 단
2 x 1 = 2 2 x 2 = 4 
4 단
4 x 1 = 4 4 x 2 = 8 4 x 3 = 12 4 x 4 = 16 
6 단
6 x 1 = 6 6 x 2 = 12 6 x 3 = 18 6 x 4 = 24 6 x 5 = 30 6 x 6 = 36 
8 단
8 x 1 = 8 8 x 2 = 16 8 x 3 = 24 8 x 4 = 32 8 x 5 = 40 8 x 6 = 48 8 x 7 = 56 8 x 8 = 64 


In [4]:
# while문의 무한 루프 사용
# 1부터 시작해서 모든 짝수와 3의 배수를 더해서
# 그합이 언제 1000을 넘어서는지 
# 1000 넘어선 값은 얼마인지

num = 1
sum = 0

while True :
    # 합의 조건식
    if num%2==0 or num%3==0 :
        sum += num
    # 탈출 조건
    if sum > 1000:
        break
    # 증가식
    num += 1

print(f'{num}이 추가되었을 때 1000을 넘어갑니다. 1000을 넘긴 최초 의 값은 {sum}입니다.')





56이 추가되었을 때 1000을 넘어갑니다. 1000을 넘긴 최초 의 값은 1055입니다.


### 함수 2025.06.11

In [6]:
# 함수 : 데이터를 받고 처리(연산)하고 결과를 반환하는 코드들의 묶음 
#       -> 호출을 통해 코드를 실행
# 중복코드를 줄일 수 있다. => 유지보수, 관리가 수월해진다!
# def 함수이름(매개변수, 매개변수, 매개변수, ....) :
#   처리작업 코드들...
#   return 값(data : 파이썬에서 제공하는 타입의 모든 데이터)

In [ ]:
# 함수정의
# 숫자 두개를 받아  => 매개변수 : 선택사항
# 덧셈연산을 하고   => 내부 처리 작업
# 결과 값을 반환    => 반환 값 : 선택사항택사항
def add(n1, n2) : # 함수 정의 : 이름, 매개변수
    result = n1 + n2 # 연산, 처리, 작업
    return result   # 결과 값 반환

In [10]:
print(type(add))

<class 'function'>


In [ ]:
add(10, 20) # 호출 : 이름과 괄호()안에 매개변수가 받을 수 있는 데이터를 함께 전달

30

In [12]:
add(1 , 5)

6

In [21]:
# 매개변수가 없는 함수
def alert_msg():
    # ....
    msg = '''
안녕하세요.
회원님
반갑습니다.!!!!
    '''
    return msg

In [22]:
print(alert_msg())


안녕하세요.
회원님
반갑습니다.!!!!
    


In [26]:
# 매개변수는 있고, 반환값이 없는 함수
# 숫자 두개를 받아 
# 덧셈연산의, 결과를 출력하는 함수
def add_print(n1, n2):
    result = n1 + n2
    print(f'{n1}+{n2}={n1+n2}')
    

In [28]:
add_print(100, 20)

100+20=120


In [29]:
result_add_print = add_print(10, 200)

10+200=210


In [31]:
print(result_add_print)

None


In [1]:
# 매개변수도 없고, 반환도 없는 함수
def display_menu() :
    menu = '''
1. 아메리카노
2. 라떼
3. 에스프레소
4. Milk Tea
'''
    print(menu)


In [2]:
display_menu()


1. 아메리카노
2. 라떼
3. 에스프레소
4. Milk Tea



In [34]:
len('hello')

5

In [35]:
def sub(n1, n2):
    return n1-n2

In [38]:
sub(n2=3, n1=10)

7

In [41]:
print('KING', 'hello', sep='\t', end='\t' )   
print('hi~!!')

KING	hello	hi~!!


In [43]:
# 매개변수가 여러개인데 몇개인지 몰라???!!!!
print('king')
print(1,2,3,4,5)

king
1 2 3 4 5


In [48]:
# 매개변수에서 전달되는 숫자들(몇개?)을 
# 모두 더한 값을 
# 반환 하는 함수

def add_sum(*args) :
    print(type(args))
    print(args)
    sum = 0
    for num in args:
        sum += num
    return sum

In [50]:
add_sum(1,2,3,4,5,6,7,8,9,10)

<class 'tuple'>
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


55

In [52]:
# 연산의 타입을 전달 받고 전달되는 숫자들을 
# 연산한 결과를 
# 반환하는 함수
def add_type(type, *args):
    # add, mul
    if type=='add':
        result = 0
        for num in args:
            result += num
        return result
    elif type=='mul':
        result = 1
        for num in args:
            result *= num
        return result
    else :
        print('사용가능한 타입을 입력해주세요!')

In [55]:
add_type('add', 1,2,3,4,5,6,7,8,9)
add_type('mul', 1,2,3,4)
add_type('sub', 1,2,3,4)

사용가능한 타입을 입력해주세요!


In [59]:
def print_args(**args):
    print(args)
    print(type(args))
    return args

In [57]:
print_args(name='손흥민', age=20)

{'name': '손흥민', 'age': 20}
<class 'dict'>


In [58]:
player1 = {
    'name' : '손흥민',
    'age' : 20
}

In [60]:
player2 = print_args(name='메시', age=30)

{'name': '메시', 'age': 30}
<class 'dict'>


In [61]:
print(player1)
print(player2)

{'name': '손흥민', 'age': 20}
{'name': '메시', 'age': 30}


In [62]:
def add_mul_return(n1, n2):
    add_result = n1 + n2
    mul_result = n1 * n2
    return (add_result, mul_result)

In [64]:
result1, result2 =  add_mul_return(10,20)
print(result1, result2)

30 200


In [65]:
add_mul_return()

TypeError: add_mul_return() missing 2 required positional arguments: 'n1' and 'n2'

In [66]:
# 매개변수의 기본값 설정
def add2(n1=0, n2=0):
    return n1+n2

In [68]:
add2(1)

1

In [69]:
# 이름, 나이, 성별 받아서 출력 함수
def say_hi(name, age, gender=True) : # Gender=True => 여성
    print(f'안녕하세요. 저는 {name}입니다. 나이는 {age} 입니다.')
    if gender:
        print('여성입니다.')
    else :
        print('남성입니다.')

In [71]:
say_hi('king', 20, False)

안녕하세요. 저는 king입니다. 나이는 20 입니다.
남성입니다.


In [72]:
# 변수의 사용 범위

a = 1

def var_test(a):
    print('함수 내부의 a : ', a)


In [73]:
var_test(10)

함수 내부의 a :  10


In [75]:
print(a)

1


In [80]:
def var_test2():
    global a
    a = a + 1
    print(a)
    

In [81]:
var_test2()

2


In [82]:
print(a)

2


In [83]:
# lambda 함수 => 한줄로 간단하게 표현하는 함수 표현식
# 함수이름 = lambda arg1, arg2 ... : 연산
# 숫자 두개를 전달받아 덧셈한 결과를 반환하는 함수
add3 = lambda n1, n2 : n1+n2

In [84]:
add3(100, 10)

110

In [85]:
type(add3)

function

In [86]:
# 내장함수 : 파이썬 설치 -> 기본으로 제공하는 함수
st_names = ['king', 'cool', 'hot', 'scott']

In [88]:
# 학생들의 index 값을 함께 출력
num = 0
for name in st_names:
    print(num, name)
    num += 1

0 king
1 cool
2 hot
3 scott


In [91]:
for index, name in enumerate(st_names, start=10):
    print(index, name)

10 king
11 cool
12 hot
13 scott


In [92]:
# filter : 필터링(매개변수로 전달되는 함수 : 요소값을 판단해서 논리값 반환)을 통해 새로운 리스트를 생성 반환
# filter(fn, itr)
def positive(l) :
    result = []
    for n in l :
        if n > 0 :
            result.append(n)
    return result

In [93]:
positive([3, 1, -1, -3, 0, 9, 10, 4])

[3, 1, 9, 10, 4]

In [95]:
# filter
# 판별함수
def positive_fn(x):
    return x > 0

In [98]:
def pos_fn2(x):
    return x%2==1

In [99]:
list(filter(pos_fn2, [3, 1, -1, -3, 0, 9, 10, 4]))

[3, 1, -1, -3, 9]

In [101]:
list(filter(lambda x : x%2==1, [3, 1, -1, -3, 0, 9, 10, 4]))

[3, 1, -1, -3, 9]

In [104]:
list(map(lambda x: x*10, [1,2,3,4,5]))

[10, 20, 30, 40, 50]

In [105]:
# 파이썬의 입출력(자원)
# 표준 입출력 => input, print
# 텍스트 파일(자원) : 입출력 I/O
# 파일 단위 입출력 : open(자원의경로, 모드)  모드 => r(read), w(write), a(append)
f = open('new_text.txt', 'w')
f.close()

In [109]:
f = open('new_text.txt', 'w') #1.파일 오픈 : w
f.write('안녕하세요!!!') # 3. 텍스트 쓰기
f.close()

In [111]:
f = open('new_text.txt', 'w')
for i in range(1, 11):
    f.write(f'{i}번째 줄 입력 \n')
f.close()

In [114]:
# 파일 내용 읽어오기
f = open('new_text.txt', 'r') # 1. 파일 열고 , Read -> r
line1 = f.readline()
print(line1)
line2 = f.readline()
print(line2)
f.close()


1번째 줄 입력 

2번째 줄 입력 



In [115]:
# 파일 내용 읽어오기
f = open('new_text.txt', 'r') # 1. 파일 열고 , Read -> r

while 1:
    line = f.readline()
    if not line:
        break
    print(line, end='')

f.close()

1번째 줄 입력 
2번째 줄 입력 
3번째 줄 입력 
4번째 줄 입력 
5번째 줄 입력 
6번째 줄 입력 
7번째 줄 입력 
8번째 줄 입력 
9번째 줄 입력 
10번째 줄 입력 


In [124]:
f = open('new_text.txt', 'r')
lines = f.readlines()
print(lines)
for line in lines:
    print(line, end='')
f.close()

['1번째 줄 입력 \n', '2번째 줄 입력 \n', '3번째 줄 입력 \n', '4번째 줄 입력 \n', '5번째 줄 입력 \n', '6번째 줄 입력 \n', '7번째 줄 입력 \n', '8번째 줄 입력 \n', '9번째 줄 입력 \n', '10번째 줄 입력 \n', '새로운 행이 추가됩니다.새로운 행이 추가됩니다. \n', '새로운 행이 추가됩니다. \n', '새로운 행16이 추가됩니다. \n', '새로운 행17이 추가됩니다. \n', '새로운 행18이 추가됩니다. \n', '새로운 행19이 추가됩니다. \n', '새로운 행20이 추가됩니다. \n']
1번째 줄 입력 
2번째 줄 입력 
3번째 줄 입력 
4번째 줄 입력 
5번째 줄 입력 
6번째 줄 입력 
7번째 줄 입력 
8번째 줄 입력 
9번째 줄 입력 
10번째 줄 입력 
새로운 행이 추가됩니다.새로운 행이 추가됩니다. 
새로운 행이 추가됩니다. 
새로운 행16이 추가됩니다. 
새로운 행17이 추가됩니다. 
새로운 행18이 추가됩니다. 
새로운 행19이 추가됩니다. 
새로운 행20이 추가됩니다. 


In [122]:
# append : 데이터 추가
f = open('new_text.txt', 'a')
f.write('새로운 행이 추가됩니다. \n')
f.close()

In [123]:
# append : 데이터 추가
f = open('new_text.txt', 'a')
for i in range(16, 21):
    f.write(f'새로운 행{i}이 추가됩니다. \n')
f.close()

In [125]:
# close 생략 가능한구현 => with
with open('new_text.txt', 'r') as file :
    lines = file.readlines()
    print(lines)

['1번째 줄 입력 \n', '2번째 줄 입력 \n', '3번째 줄 입력 \n', '4번째 줄 입력 \n', '5번째 줄 입력 \n', '6번째 줄 입력 \n', '7번째 줄 입력 \n', '8번째 줄 입력 \n', '9번째 줄 입력 \n', '10번째 줄 입력 \n', '새로운 행이 추가됩니다.새로운 행이 추가됩니다. \n', '새로운 행이 추가됩니다. \n', '새로운 행16이 추가됩니다. \n', '새로운 행17이 추가됩니다. \n', '새로운 행18이 추가됩니다. \n', '새로운 행19이 추가됩니다. \n', '새로운 행20이 추가됩니다. \n']


In [127]:
# 예외처리 : 에러 발생시에 비정상적인 종료 막기 위한 처리
print(10/0)
print('프로그램 종료')

ZeroDivisionError: division by zero

In [128]:
list_t = [1,2,3]
print(list_t[3])

IndexError: list index out of range

In [130]:
print(list_t[-4])

IndexError: list index out of range

In [131]:
userName

NameError: name 'userName' is not defined

In [132]:
dict_t = {
    'name' : 'SON'
}

In [133]:
dict_t['age']

KeyError: 'age'

In [134]:
f = open('new_text1.txt', 'r')
f. close()

FileNotFoundError: [Errno 2] No such file or directory: 'new_text1.txt'

In [135]:
add()

TypeError: add() missing 2 required positional arguments: 'n1' and 'n2'

In [140]:
try :
    print(10/5)  # 에러 예상 위치
except:
    print('에러가 발생했습니다. 에러에대한 처리를 합니다.')

print('프로그램을 종료합니다.')

2.0
프로그램을 종료합니다.


In [144]:
try :
    print(10/2)
    print(list_t[1]) # <=======
    print(uname)
except ZeroDivisionError as e :
    print('0으로 나누는 연산을 불가능합니다.')
    print(e)
except (NameError, IndexError) as e:
    #print('정의되지 않은 식별자 입니다.')
    print('에러가 발생했습니다.')
    print(e)
# except IndexError as e:
#     print('리스트의 index 범위에서 벗어납니다')
#     print(e)
except :
    print('에러발생!!!')

5.0
2
에러가 발생했습니다.
name 'uname' is not defined


In [146]:
# try: except: finally: -> 에러 발생여부와 상관없이 실행되어야 하는 블록
try:
    print('hello')
    print(10/2)
except:
    print('error!!')
finally:
    print('!!!!!')

hello
5.0
!!!!!


In [151]:
try :
    age = int(input('나이를 입력하세요'))
except:
    print('숫자형식으로 입력해주세요!!!!!!')
else :
    if age > 18 :
        print('입장')
    else :
        print('불가')


입장


In [152]:
# 사용자 정의 예외 타입 정의
# 논리적인 오류 발생 -> 예외로 처리
# age => 음수, 500 : 논리적 오류

class MyError(Exception):
    pass

In [153]:
# 에러 강제 발생
raise MyError()

MyError: 

In [158]:
try:
    age = int(input('나이를 입력하세요!'))
        
    if age<1 or age>200:
        raise MyError()
    
except MyError :
    print('나이의 입력 범위는 1~200 까지입니다.\n다시입력하세요!')
except:
    print('다시입력하세요!')
else :
    print(age)

다시입력하세요!


### 2025.06.12

In [ ]:
# 객체지향 프로그래밍 : 객체의 개념을 프로그램이에 도입
# 객체 : 변수들, 함수들도 구성 => 메모리에 올라가 있는 상태
# 클래스 : 변수들과 함수들이 어떻게 구성되는지의 설계도 -> 변수들을 정의, 함수들을 정의의
# => 클래스만 정의했다 -> 사용 X, 클래스를 이용해서 객체로 만들어야 사용가능
# class 클래스이름:
#     변수들과 함수들을 정의
# 클래스의 정의 => 새로운 사용자 정의 타입을 만든것!
# 객체 생성 => 변수 = 클래스이름()
# 객체의 활용 => 변수.객체가가지는변수, 변수.객체가가지는함수()  메서드(객체가 가지는 함수)
# 클래스 정의
class Cookie:
    pass

In [5]:
# 객체 생성
c1 = Cookie()
c2 = Cookie()

In [6]:
print(id(c1), type(c1))
print(id(c2), type(c2))

1881564817488 <class '__main__.Cookie'>
1881564818128 <class '__main__.Cookie'>


In [29]:
# 사칙연산을 하는 클래스 정의 : 클래스이름, 변수, 함수
# 변수는 두개, 함수(메서드) 4개
class FourCal:

    # 초기화(변수 선언->최초 데이터를 할당당) 메서드 => 생성자, 생성자함수 
    # 필요한 변수들의 생성, 값을 초기화
    def __init__(self, first, second):
        self.first = first
        self.second = second

    # 클래스에서 함수를 정의할 때에는 반드시 self 매개변수를 받아야한다!
    # self => 객체 자시을 가르키는 변수(객체의 주소)
    def setdata(self, first, second):
        self.first = first
        self.second = second
    
    # 사칙연산 함수
    def add(self):
        return self.first+self.second
    
    def sub(self):
        return self.first-self.second
    
    def mul(self):
        return self.first*self.second
    
    def div(self):
        return self.first/self.second



In [8]:
cal_1 = FourCal()

In [9]:
type(cal_1)

__main__.FourCal

In [11]:
cal_1.setdata(10, 20)

In [12]:
print(cal_1.first, cal_1.second)

10 20


In [13]:
cal_2 = FourCal()

In [14]:
cal_2.first

AttributeError: 'FourCal' object has no attribute 'first'

In [16]:
cal_3 = FourCal()

TypeError: FourCal.__init__() missing 2 required positional arguments: 'first' and 'second'

In [21]:
cal_4 = FourCal(100, 200)

In [22]:
cal_4.first
cal_4.second

200

In [30]:
cal_5 = FourCal(10, 7)

In [34]:
print(cal_5.first, cal_5.second)
print(cal_5.add())
print(cal_5.sub())
print(cal_5.mul())
print(cal_5.div())

10 7
17
3
70
1.4285714285714286


In [ ]:
# 학생 class 생성 -> 객체 생성 
# 변수: 학번, 이름, 국어점수, 영어점수, 수학점수
# 기능: 전체 데이터 출력하는 메서드 (이름, 학번, 총점, 평균)
#       총점 계산
#       평균 계산
# 시뮬레이션 : 테스트 학생 데이터 생성-> 결과 출력
class Student:
    
    # 데이터 초기화
    def __init__(self, name, sno, k_score, e_score, m_score):
        self.s_name = name
        self.s_no = sno
        self.k_score = k_score
        self.e_score = e_score
        self.m_score = m_score

    def sum(self):
        return self.k_score + self.e_score + self.m_score
    
    def avg(self):
        return self.sum()/3

    def print_result(self):
        print('성적표', '-'*20)
        print(f'이름: {self.s_name} ({self.s_no})')
        print('국어 :', self.k_score)
        print('영어 :', self.e_score)
        print('수학 :', self.m_score)
        print('총점 :', self.sum())
        print('평균 :', self.avg())


In [36]:
st_1 = Student()

In [37]:
type(st_1)

__main__.Student

In [43]:
st_2 = Student('손흥민', 12345, 80, 70, 50)

In [44]:
st_2.print_result()

성적표 --------------------
이름: 손흥민 (12345)
국어 : 80
영어 : 70
수학 : 50
총점 : 200
평균 : 66.66666666666667


In [46]:
students = [
    Student('손흥민1', 123451, 80, 70, 50),
    Student('손흥민2', 123452, 80, 70, 50),
    Student('손흥민3', 123453, 80, 70, 50),
    Student('손흥민4', 123454, 80, 70, 50),
    Student('손흥민5', 123455, 80, 70, 50),
]

In [47]:
for s in students:
    s.print_result()

성적표 --------------------
이름: 손흥민1 (123451)
국어 : 80
영어 : 70
수학 : 50
총점 : 200
평균 : 66.66666666666667
성적표 --------------------
이름: 손흥민2 (123452)
국어 : 80
영어 : 70
수학 : 50
총점 : 200
평균 : 66.66666666666667
성적표 --------------------
이름: 손흥민3 (123453)
국어 : 80
영어 : 70
수학 : 50
총점 : 200
평균 : 66.66666666666667
성적표 --------------------
이름: 손흥민4 (123454)
국어 : 80
영어 : 70
수학 : 50
총점 : 200
평균 : 66.66666666666667
성적표 --------------------
이름: 손흥민5 (123455)
국어 : 80
영어 : 70
수학 : 50
총점 : 200
평균 : 66.66666666666667


In [62]:
# 클래스의 상속 : 새로운 클래스를 만들때 기존의 클래스의 멤버들을 받아서 생성하는 방법
# class 클래스이름(부모클래스)
class MoreFourCal(FourCal):
    def pow(self):
        return self.first**self.second
    
    def div(self):
        if self.second == 0 :
            return 0
        else :
            return self.first/self.second

In [49]:
mcal_1 = MoreFourCal()

TypeError: FourCal.__init__() missing 2 required positional arguments: 'first' and 'second'

In [50]:
mcal_1 = MoreFourCal(100, 8)

In [54]:
print(mcal_1.add())
print(mcal_1.sub())
print(mcal_1.mul())
print(mcal_1.div())

108
92
800
12.5


In [63]:
mcal_2 = MoreFourCal(100, 0)

In [64]:
print(mcal_2.add())
print(mcal_2.mul())
print(mcal_2.div())
print(mcal_2.pow())

100
0
0
1


### 표준모듈

In [1]:
import datetime

In [2]:
day1 = datetime.date(2025, 6, 12)

In [4]:
print(day1)

2025-06-12


In [5]:
day2 = datetime.date(2025, 1, 1)

In [6]:
print(day1-day2)

162 days, 0:00:00


In [7]:
import time

In [8]:
time.time()

1749711409.0991209

In [ ]:
time.localtime()

time.struct_time(tm_year=2025, tm_mon=6, tm_mday=12, tm_hour=15, tm_min=57, tm_sec=20, tm_wday=3, tm_yday=163, tm_isdst=0)

In [10]:
time.ctime()

'Thu Jun 12 15:58:32 2025'

In [11]:
import random

In [35]:
random.random() #  0.00000000 <= R < 1

0.7639145556730687

In [59]:
random.randint(60, 100)

99

In [63]:
list_score = []
for s in range(0,10):
    list_score.append(random.randint(60, 100))

print(list_score)

[98, 73, 88, 73, 63, 72, 75, 66, 72, 89]


In [71]:
random.choice([1,2,3,4,5,6,7,8])

4

In [81]:
random.sample([1,2,3,4,5,6,7,8,9], 5)

[1, 6, 2, 9, 3]

In [82]:
import os

In [83]:
os.environ

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\LG\\AppData\\Roaming',
        'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_11884_QTRZGHRSOFLIGXVW',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'DESKTOP-9N5PTRO',
        'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'EFC_14880_1262719628': '1',
        'EFC_14880_1592913036': '1',
        'EFC_14880_2283032206': '1',
        'EFC_14880_2775293581': '1',
        'EFC_14880_3789132940': '1',
        'ELECTRON_RUN_AS_NODE': '1',
        'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
        'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\LG',
        'JPY_INTERRUPT_EVENT': '2088',
     

In [84]:
os.chdir('c:\\windows')

In [88]:
os.getcwd()

'C:\\project\\py_project'

In [87]:
os.chdir('C:\\project\\py_project')

In [89]:
os.mkdir('test')

In [90]:
os.rmdir('test')

In [91]:
import json

In [92]:
with open('data.json', 'r', encoding='utf8') as f :
    data = json.load(f)

In [94]:
print(data, type(data))

{'name': '손흥민', 'age': 30, 'number': 7} <class 'dict'>


In [95]:
json_str_data = json.dumps(data)

In [97]:
print(json_str_data, type(json_str_data))

{"name": "\uc190\ud765\ubbfc", "age": 30, "number": 7} <class 'str'>


In [99]:
import numpy as np

In [100]:
arr = np.array([1,2,3,4,5])

In [102]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [103]:
arr + 10

array([11, 12, 13, 14, 15])

In [106]:
# 배열의 생성
# 0으로 채워지는 배열 생성
zeros = np.zeros((1,3))
print(zeros)

[[0. 0. 0.]]


In [109]:
# 1로 채우는 배열
ones = np.ones((5,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [112]:
# 일련번호 생성되는 배열
# 0~10 사이의 숫자를 2씩 간격으로 생성
seq_1 = np.arange(1, 10, 3)
print(seq_1)

[1 4 7]


In [117]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 0~1 5개로 구분
linspace = np.linspace(1, 10, 4)
print(linspace)

[ 1.  4.  7. 10.]


In [ ]:
# 배열의 속성 확인
arr1 = np.array([[1,2,3],[4,5,6]])

In [130]:
print(type(arr1))
print(arr1.shape)   # 배열의 크기 (행, 열) => (3,3)
print(arr1.ndim)    # 배열의 차원 : 2
print(arr1.size)    # 요소의 개수 : 6
print(arr1.dtype)   # int64

<class 'numpy.ndarray'>
(2, 3)
2
6
int64
